FROM docker.elastic.co/elasticsearch/elasticsearch:7.9.2
COPY --chown=elasticsearch:elasticsearch ./elasticsearch.yml /usr/share/elasticsearch/config/

# Run as belows
# docker build --tag=elasticsearch-custom .
# docker run -ti -v /usr/share/elasticsearch/data elasticsearch-custom